import mongoose from 'mongoose'
import { STAGE_KEYS } from '../constants/scenarioDefinition.js'
import { EVENT_CODES, INTENTS, LOCAL_CONSEQUENCES, METADATA_ALLOWLIST } from '../constants/scenarioEngine.js'

const { Schema } = mongoose

/**
 * ScenarioEvent - the client contract's `Event` entity (specification section 6):
 * event_id, run_id, sequence, event_code, client_ts, elapsed_ms, synthetic_target_id,
 * points_delta, metadata_allowlist.
 *
 * Named ScenarioEvent rather than Event because `Event` is too generic for a global
 * Mongoose model name; the collection is `scenarioevents`. This is the client's Event.
 *
 * THIS LEDGER IS THE AUDIT SOURCE OF TRUTH. `ScenarioRun.score_running` is a cache that
 * must always be reproducible by summing `points_delta` over a run's events.
 *
 * `_id` is the event_id.
 */

/**
 * Constrained metadata. Not a free-form bag: every key is on the allowlist and every
 * value is a bounded scalar. The client's privacy criterion requires event logs to use an
 * allowlist, and an open object is how learner-typed content, secrets or markup leak into
 * a log. Rationale is NOT stored here - it lives in its own validated field on the run.
 */
const metadataSchema = new Schema(
  {
    intent: { type: String, enum: INTENTS },
    transition: { type: String },
    consequence: { type: String, enum: LOCAL_CONSEQUENCES },
    resolution_code: { type: String },
    dwell_ms: { type: Number, min: 0, max: 86_400_000 },
    open_latency_ms: { type: Number, min: 0, max: 86_400_000 },
    link_hover_ms: { type: Number, min: 0, max: 86_400_000 },
    /**
     * `in_message_contact` is the value every client surface sends for
     * `verify_in_message_contact` (the action sheet and all authored scenes). The enum only
     * listed `in_message`, so that route was refused with a 422 in a real browser while every
     * stubbed test passed - found by IMMERSIVE-003E's browser verification. `in_message` is
     * kept so nothing already stored becomes invalid. Metadata only: no score reads it.
     */
    verify_source: {
      type: String,
      enum: ['trusted_directory', 'known_app', 'known_number', 'in_message', 'in_message_contact'],
    },
    premature: { type: Boolean },
  },
  { _id: false },
)

const scenarioEventSchema = new Schema(
  {
    run_id: { type: Schema.Types.ObjectId, ref: 'ScenarioRun', required: true },

    /** Strictly increasing from 1, no gaps. Unique per run. */
    sequence: { type: Number, required: true, min: 1 },

    /** Server-decided. The client never supplies this. */
    event_code: { type: String, enum: EVENT_CODES, required: true },

    /** The stage the run was in when this event was accepted. */
    stage: { type: String, enum: STAGE_KEYS, required: true },

    /** Server-decided, read from the ScenarioDefinition. The client never supplies it. */
    points_delta: { type: Number, required: true, min: -10, max: 10 },

    /** Must name an asset declared by the pinned ScenarioDefinition, or be null. */
    synthetic_target_id: { type: String, default: null },

    /**
     * Idempotency key, generated by the client, one per learner action. Unique, so a
     * retried request cannot produce a second event or a second scoring effect.
     */
    intent_key: { type: String, required: true, trim: true, maxlength: 128 },

    /** Telemetry only. Never used to decide a transition, a score or an outcome. */
    client_ts: { type: Date, default: null },
    elapsed_ms: { type: Number, default: null, min: 0, max: 86_400_000 },

    /** Server clock. This is the authoritative audit timestamp. */
    server_ts: { type: Date, required: true, default: Date.now },

    metadata: { type: metadataSchema, default: () => ({}) },
  },
  { timestamps: true },
)

/** Idempotency: one event per learner action, however many times it is retried. */
scenarioEventSchema.index({ intent_key: 1 }, { unique: true })
/** Ordering: no duplicate or interleaved sequence numbers within a run. */
scenarioEventSchema.index({ run_id: 1, sequence: 1 }, { unique: true })

/** Ledger view for replay and admin. Not a candidate projection. */
scenarioEventSchema.methods.toLedgerJSON = function toLedgerJSON() {
  return {
    event_id: this._id.toString(),
    run_id: this.run_id.toString(),
    sequence: this.sequence,
    event_code: this.event_code,
    stage: this.stage,
    points_delta: this.points_delta,
    synthetic_target_id: this.synthetic_target_id,
    server_ts: this.server_ts,
    metadata: this.metadata,
  }
}

export const ScenarioEvent = mongoose.model('ScenarioEvent', scenarioEventSchema)
export { METADATA_ALLOWLIST }
