import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { cleanup, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { AdminLayout } from '@/components/admin/AdminLayout'
import { ROUTES } from '@/constants/routes'
import { RequireAdmin } from '@/routes/RequireAdmin'
import { AdminDashboardPage } from '@/pages/AdminDashboardPage'
import {
  DASHBOARD_EMPTY,
  PROFILE,
  createAdminServer,
  installAdminFetch,
} from '@/test/adminFixtures'

/**
 * ENHANCEMENT-001 - the instructor dashboard, through the real guard, shell and `adminApi`
 * against a stubbed `fetch` serving a payload generated by the backend aggregator itself.
 *
 * The screen is a presentation layer: these tests check that the server's figures are
 * shown, that highest/lowest come from the server rather than being worked out here, that
 * no learner is identified, and that an empty or failing installation still reads clearly.
 */

let server

beforeEach(() => {
  server = createAdminServer()
  installAdminFetch(server)
})

afterEach(() => {
  cleanup()
  vi.unstubAllGlobals()
  delete globalThis.fetch
})

function renderDashboard() {
  return render(
    <MemoryRouter initialEntries={[ROUTES.ADMIN]}>
      <Routes>
        <Route element={<RequireAdmin />}>
          <Route element={<AdminLayout />}>
            <Route path={ROUTES.ADMIN} element={<AdminDashboardPage />} />
          </Route>
        </Route>
        <Route path={ROUTES.ADMIN_LOGIN} element={<p>Administrator sign in</p>} />
      </Routes>
    </MemoryRouter>,
  )
}

/** The payload has arrived and rendered - not merely the page heading. */
const loaded = () => screen.findByText('Highest malicious success')

const dashboardCalls = () => server.calls.filter((call) => call.path === '/admin/dashboard')

describe('the dashboard boundary', () => {
  it('sends an unauthenticated visitor to sign-in without requesting any figures', async () => {
    server.authenticated = false
    renderDashboard()
    expect(await screen.findByText('Administrator sign in')).toBeTruthy()
    expect(dashboardCalls()).toHaveLength(0)
  })

  it('is the instructor landing page and is marked current in the navigation', async () => {
    renderDashboard()
    await screen.findByRole('heading', { level: 1, name: 'Dashboard' })
    const nav = screen.getByRole('navigation', { name: /instructor sections/i })
    const link = within(nav).getByRole('link', { name: 'Dashboard' })
    expect(link.getAttribute('aria-current')).toBe('page')
    for (const name of ['Scenarios', 'Attempts', 'Settings', 'Audit log']) {
      expect(within(nav).getByRole('link', { name })).toBeTruthy()
    }
  })
})

describe('the figures', () => {
  it('shows the headline figures the server counted', async () => {
    renderDashboard()
    await loaded()

    const learners = screen.getByText('Learners').closest('div').parentElement
    expect(within(learners).getByText('5')).toBeTruthy()
    expect(within(learners).getByText(/2 with a completed assessment · 1 archived/)).toBeTruthy()

    const completed = screen.getByText('Completed attempts').closest('div').parentElement
    expect(within(completed).getByText('3')).toBeTruthy()
    expect(within(completed).getByText(/of 5 started · 60% completed/)).toBeTruthy()

    const average = screen.getByText('Average score', { selector: 'p' }).closest('div').parentElement
    expect(within(average).getByText('68.3')).toBeTruthy() // server mean of 72, 38, 95
    expect(within(average).getByText(/median 72/)).toBeTruthy()
    const range = screen.getByText('Score range', { selector: 'p' }).closest('div').parentElement
    expect(within(range).getByText('38–95')).toBeTruthy()
  })

  it('names the highest and lowest malicious scenario success from the server, with its evidence', async () => {
    renderDashboard()
    await loaded()

    const highest = screen.getByText('Highest malicious success').parentElement
    expect(within(highest).getByText('WhatsApp')).toBeTruthy()
    expect(within(highest).getByText('67%')).toBeTruthy()
    expect(within(highest).getByText(/2 of 3 malicious/)).toBeTruthy()

    const lowest = screen.getByText('Lowest malicious success').parentElement
    expect(within(lowest).getByText('Email')).toBeTruthy()
    expect(within(lowest).getByText('0%')).toBeTruthy()
  })

  it('switches the platform measure without another request, and explains it', async () => {
    const user = userEvent.setup()
    renderDashboard()
    await loaded()
    const before = dashboardCalls().length

    await user.click(screen.getByRole('radio', { name: 'Malicious success' }))

    expect(screen.getByText(/Lower is better/)).toBeTruthy()
    const bars = screen.getByRole('list', { name: 'Malicious scenario success by platform' })
    expect(within(bars).getAllByRole('listitem')).toHaveLength(4)
    expect(within(bars).getByText('Highest')).toBeTruthy()
    expect(dashboardCalls()).toHaveLength(before)
  })

  it('shows the full platform table with the counts behind each rate', async () => {
    renderDashboard()
    await loaded()

    const table = screen.getByRole('table')
    expect(table.querySelector('caption')).toBeTruthy()
    expect(table.parentElement.className).toContain('overflow-x-auto')
    const whatsapp = within(table).getByText('WhatsApp').closest('tr')
    expect(within(whatsapp).getByText('67%')).toBeTruthy()
    expect(within(whatsapp).getByText('(2/3)')).toBeTruthy()
  })

  it('identifies no learner anywhere on the page', async () => {
    const { container } = renderDashboard()
    await loaded()
    expect(container.textContent).not.toContain(PROFILE.display_name)
    expect(container.textContent).not.toContain(PROFILE.service_no_masked)
  })
})

describe('assessment only (ENHANCEMENT-001B)', () => {
  it('requests the dashboard with no parameters and offers no mode switch', async () => {
    renderDashboard()
    await loaded()
    expect(dashboardCalls().every((call) => call.search === '')).toBe(true)

    for (const name of ['Training', 'Both modes', 'Assessment']) {
      expect(screen.queryByRole('radio', { name })).toBeNull()
    }
    expect(screen.queryByText(/both modes/i)).toBeNull()
    expect(screen.queryByText(/training/i)).toBeNull()
  })

  it('refreshes through the same parameterless request', async () => {
    const user = userEvent.setup()
    renderDashboard()
    await loaded()
    const before = dashboardCalls().length

    await user.click(screen.getByRole('button', { name: /refresh/i }))
    await waitFor(() => expect(dashboardCalls().length).toBe(before + 1))
    expect(dashboardCalls().at(-1).search).toBe('')
  })
})

describe('score ranges', () => {
  const rangeRows = () => {
    const list = screen.getByRole('list', { name: 'Completed assessment attempts by score range' })
    // Label and count are separate cells; the bar between them is decorative.
    return within(list).getAllByRole('listitem').map((item) => [...item.children]
      .map((cell) => cell.textContent.replace(/\s+/g, ' ').trim())
      .filter(Boolean)
      .join(' '))
  }

  it('sums the server bands into 70+, 50–69 and Below 50, keeping an empty range at 0', async () => {
    renderDashboard()
    await loaded()

    expect(screen.getByRole('heading', { name: 'Score ranges' })).toBeTruthy()
    // Fixture bands: one attempt in 30-39, one in 70-79, one in 90-100.
    expect(rangeRows()).toEqual([
      '70+ 2 attempts · 67%',
      '50–69 0 attempts · 0%',
      'Below 50 1 attempt · 33%',
    ])
    expect(screen.getByText('Based on 3 completed attempts, scored out of 100.')).toBeTruthy()
  })

  it('shows all three ranges at 0 before any attempt is completed', async () => {
    server.dashboard = DASHBOARD_EMPTY
    renderDashboard()
    await screen.findByText('Nothing to compare yet')

    expect(rangeRows()).toEqual(['70+ 0 attempts', '50–69 0 attempts', 'Below 50 0 attempts'])
  })
})

describe('little or no data', () => {
  it('reads clearly on a new installation', async () => {
    server.dashboard = DASHBOARD_EMPTY
    renderDashboard()
    await screen.findByText('Nothing to compare yet')

    expect(screen.getAllByText('No completed attempts yet').length).toBeGreaterThan(0)
    expect(screen.getByText('Nothing to compare yet')).toBeTruthy()
    expect(screen.getByText('No attempts started yet')).toBeTruthy()
    expect(screen.queryByRole('tooltip')).toBeNull()
  })

  it('reports a server error with its own message and can retry', async () => {
    const user = userEvent.setup()
    server.failNext = { status: 500, code: 'SERVER_ERROR', message: 'The dashboard could not be built.' }
    renderDashboard()

    expect(await screen.findByText('The dashboard could not be built.')).toBeTruthy()
    await user.click(screen.getByRole('button', { name: /try again/i }))
    expect(await loaded()).toBeTruthy()
  })
})

describe('accessibility', () => {
  it('keeps every interactive target at least 44px tall', async () => {
    const { container } = renderDashboard()
    await loaded()
    const controls = [...container.querySelectorAll('select, button, a[href], input')]
    const tooSmall = controls.filter((element) => {
      const classes = element.className
      if (typeof classes !== 'string') return false
      return /\bh-9\b|\bh-8\b|\bh-10\b/.test(classes) && !/min-h-11/.test(classes)
    })
    expect(tooSmall).toEqual([])
  })

  it('gives each chart column a spoken label', async () => {
    renderDashboard()
    await loaded()
    expect(screen.getByRole('img', { name: /Score 70–79: 1 attempt$/ })).toBeTruthy()
  })
})
